/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conection_bd;
import static interfaces.loggin.icono;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author Josue Lopez
 */
public class altaEquipos extends javax.swing.JFrame {

    /**
     * Creates new form altaEquipos
     */
    public altaEquipos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource(icono)).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barra_discoduro = new javax.swing.JTextField();
        barra_fecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        barra_ubicacion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        barra_ram = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        barra_marca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        boton_aceptar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        barra_procesador = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        boton_buscar = new javax.swing.JButton();
        barra_estado = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        barra_modelo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        barra_perifericos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        barra_tipo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        barra_contra = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alta de equipos");
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel1.setBackground(new java.awt.Color(191, 191, 191));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*este campo puede dejarse vacio");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Tipo de equipo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 118, -1));

        barra_discoduro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_discoduro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_discoduro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_discoduroActionPerformed(evt);
            }
        });
        barra_discoduro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                barra_discoduroKeyTyped(evt);
            }
        });
        jPanel1.add(barra_discoduro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 210, -1));

        barra_fecha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_fecha.setPreferredSize(new java.awt.Dimension(81, 23));
        jPanel1.add(barra_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 210, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Ubicacion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 98, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Procesador:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 86, -1));

        barra_ubicacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_ubicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JM Atlacomulco", "JM Toluca", "JM Palmillas", "JM Tenango", "JM Villa Victoria", "JM Tequixquiac", "Planta Swecomex", "Bodega ISB Queretaro", "FarmTire Ixtlahuaca" }));
        jPanel1.add(barra_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 210, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Memoria ram:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        barra_ram.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_ram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4", "6", "8", "10", "12", "14", "16", "18", "20", "22", "24", "26", "28", "30", "32" }));
        jPanel1.add(barra_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 210, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 98, -1));

        barra_marca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_marca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_marcaActionPerformed(evt);
            }
        });
        jPanel1.add(barra_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 210, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Estado Actual:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 98, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Marca:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 98, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Fecha:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 98, -1));

        boton_aceptar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alta_100.png"))); // NOI18N
        boton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 100, 100));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*en caso de que la fecha se HOY no selecciones nada");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, 23));

        barra_procesador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_procesador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_procesador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_procesadorActionPerformed(evt);
            }
        });
        jPanel1.add(barra_procesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Dar de alta");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 133, -1));

        boton_buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar_30.png"))); // NOI18N
        boton_buscar.setText("Regresar");
        boton_buscar.setPreferredSize(new java.awt.Dimension(125, 30));
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 35));

        barra_estado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUENO", "REGULAR", "MALO" }));
        jPanel1.add(barra_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 210, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Modelo:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 98, 20));

        barra_modelo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_modeloActionPerformed(evt);
            }
        });
        jPanel1.add(barra_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 210, 20));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*este campo puede dejarse vacio");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Perifericos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 98, -1));

        barra_perifericos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_perifericos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_perifericos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_perifericosActionPerformed(evt);
            }
        });
        jPanel1.add(barra_perifericos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 210, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*este campo puede dejarse vacio");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        barra_tipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "LAPTOP", "ALL IN ONE" }));
        jPanel1.add(barra_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 210, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Disco duro:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 98, -1));

        barra_contra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_contra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_contraActionPerformed(evt);
            }
        });
        barra_contra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                barra_contraKeyTyped(evt);
            }
        });
        jPanel1.add(barra_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 210, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*este campo puede dejarse vacio");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barra_discoduroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_discoduroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_discoduroActionPerformed

    private void barra_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_marcaActionPerformed

    private void boton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aceptarActionPerformed
        // TODO add your handling code here:
        java.util.Date date = new java.util.Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        Date fecha_1 = new Date();
        int validacion = 0;
        String tipo, ubicacion, marca, modelo, procesador, ram, disco_duro, estado_actual, perifericos, contra;
        String fecha = "";
        tipo = barra_tipo.getSelectedItem().toString().trim().toUpperCase();
        ubicacion = barra_ubicacion.getSelectedItem().toString().trim().toUpperCase();
        marca = barra_marca.getText().trim().toUpperCase();
        modelo = barra_modelo.getText().trim().toUpperCase();
        procesador = barra_procesador.getText().trim().toUpperCase();
        ram = barra_ram.getSelectedItem().toString().trim();
        disco_duro = barra_discoduro.getText().trim().toUpperCase();
        estado_actual = barra_estado.getSelectedItem().toString().trim().toUpperCase();
        perifericos = barra_perifericos.getText().trim();
        contra = barra_contra.getText().trim();

        if (barra_fecha.getDate() == null) {
            fecha = f.format(fecha_1);
        } else {
            fecha = f.format(barra_fecha.getDate());
        }
        if (marca.equals("")) {
            barra_marca.setBackground(Color.cyan);
            marca = "NO APLICA";
        }
        if (modelo.equals("")) {
            barra_modelo.setBackground(Color.cyan);
            modelo = "NO APLICA";
        }
        if (procesador.equals("")) {
            barra_procesador.setBackground(Color.red);
            validacion++;
        }
        if (disco_duro.equals("")) {
            barra_discoduro.setBackground(Color.red);
            validacion++;
        }
        if (perifericos.equals("")) {
            barra_perifericos.setBackground(Color.cyan);
            perifericos = "NO APLICA";
        }
        if (contra.equals("")) {
            barra_perifericos.setBackground(Color.cyan);
            perifericos = "NO APLICA";
        }

        if (validacion == 0) {
            try {
                Connection cn = Conection_bd.conexion_bd();
                PreparedStatement pst = cn.prepareStatement("insert into equipos values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                pst.setInt(1, 0);
                pst.setString(2, tipo);
                pst.setString(3, ubicacion);
                pst.setString(4, marca);
                pst.setString(5, procesador);
                pst.setInt(6, Integer.parseInt(ram));
                pst.setInt(7, Integer.parseInt(disco_duro));
                pst.setString(8, estado_actual);
                pst.setInt(9, 1);
                pst.setString(10, modelo);
                pst.setString(11, fecha);
                pst.setString(12, "");
                pst.setString(13, perifericos);
                pst.setString(14, "");
                pst.executeUpdate();
                cn.close();

            } catch (Exception e) {
                System.out.println("Error al guardar: " + e);
                //JOptionPane.showMessageDialog(Componente, mensaje, título, tipo de mensaje, icono);
                JOptionPane.showMessageDialog(null, "Error al guardar\n" + e, "Error", JOptionPane.ERROR_MESSAGE);
            }
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar los campos requeridos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_aceptarActionPerformed

    private void barra_procesadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_procesadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_procesadorActionPerformed

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
        menuEquipos p = new menuEquipos();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void barra_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_modeloActionPerformed

    private void barra_perifericosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_perifericosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_perifericosActionPerformed

    private void barra_discoduroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barra_discoduroKeyTyped
        // TODO add your handling code here:
        soloNumeros(evt);
    }//GEN-LAST:event_barra_discoduroKeyTyped

    private void barra_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_contraActionPerformed

    private void barra_contraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barra_contraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_contraKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new altaEquipos().setVisible(true);
            }
        });
    }

    public void limpiarCampos() {
        barra_tipo.setBackground(Color.GREEN);
        barra_ubicacion.setBackground(Color.GREEN);
        barra_marca.setBackground(Color.GREEN);
        barra_modelo.setBackground(Color.GREEN);
        barra_procesador.setBackground(Color.GREEN);
        barra_ram.setBackground(Color.GREEN);
        barra_discoduro.setBackground(Color.GREEN);
        barra_estado.setBackground(Color.GREEN);
        barra_perifericos.setBackground(Color.GREEN);
        barra_estado.setBackground(Color.GREEN);

        Icon icono_correcto = new ImageIcon(getClass().getResource("/imagenes/correcto.png"));
        int valor = JOptionPane.showConfirmDialog(null, "Se ha guardado correctamente", "Equipo registrado correctamente", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, icono_correcto);
        //int valor = JOptionPane.showConfirmDialog(null, "Se ha guardado correctamente", "Equipo registrado correctamente", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, icono_correcto);
        if (valor == JOptionPane.YES_OPTION) {
            barra_tipo.setSelectedIndex(0);
            barra_ubicacion.setSelectedIndex(0);
            barra_ram.setSelectedIndex(0);
            barra_estado.setSelectedIndex(0);
            barra_marca.setText("");
            barra_modelo.setText("");
            barra_procesador.setText("");
            barra_discoduro.setText("");
            barra_perifericos.setText("");
            barra_fecha.setCalendar(null);
        }
        barra_tipo.setSelectedIndex(0);
        barra_tipo.setBackground(Color.white);
        barra_ubicacion.setSelectedIndex(0);
        barra_ubicacion.setBackground(Color.white);
        barra_marca.setBackground(Color.white);
        barra_modelo.setBackground(Color.white);
        barra_procesador.setBackground(Color.white);
        barra_ram.setSelectedIndex(0);
        barra_ram.setBackground(Color.white);
        barra_discoduro.setBackground(Color.white);
        barra_estado.setSelectedIndex(0);
        barra_estado.setBackground(Color.white);
        barra_perifericos.setBackground(Color.white);
        barra_estado.setSelectedIndex(0);

    }

    public void soloNumeros(java.awt.event.KeyEvent evt)// se validaran segun el codigo ascii no permite ingresar
    {
        char numero = evt.getKeyChar();
        if (Character.isLetter(numero)) {
            getToolkit().beep();
            evt.consume();
            //JOptionPane.showMessageDialog(Componente, mensaje, título, tipo de mensaje, icono);
            JOptionPane.showMessageDialog(this, "No se permiten letras en este campo", "Atencion", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barra_contra;
    private javax.swing.JTextField barra_discoduro;
    private javax.swing.JComboBox<String> barra_estado;
    private com.toedter.calendar.JDateChooser barra_fecha;
    private javax.swing.JTextField barra_marca;
    private javax.swing.JTextField barra_modelo;
    private javax.swing.JTextField barra_perifericos;
    private javax.swing.JTextField barra_procesador;
    private javax.swing.JComboBox<String> barra_ram;
    private javax.swing.JComboBox<String> barra_tipo;
    private javax.swing.JComboBox<String> barra_ubicacion;
    private javax.swing.JButton boton_aceptar;
    private javax.swing.JButton boton_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
