/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conection_bd;
import static interfaces.loggin.icono;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue Lopez
 */
public class altaResponsable extends javax.swing.JFrame {

    /**
     * Creates new form altaResponsable
     */
    public altaResponsable() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource(icono)).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registrar_boton = new javax.swing.JButton();
        barra_empleado = new javax.swing.JTextField();
        barra_area = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        boton_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alta responsable");
        setPreferredSize(new java.awt.Dimension(476, 500));

        jPanel1.setBackground(new java.awt.Color(191, 191, 191));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Nombre Empleado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Area:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        registrar_boton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registrar_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alta_100.png"))); // NOI18N
        registrar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_botonActionPerformed(evt);
            }
        });
        jPanel1.add(registrar_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 100, 101));

        barra_empleado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_empleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(barra_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 256, -1));

        barra_area.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_area.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(barra_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 256, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Registrar");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 100, -1));

        boton_regresar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar_30.png"))); // NOI18N
        boton_regresar.setText("Regresar");
        boton_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_regresarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_botonActionPerformed
        java.util.Date date = new java.util.Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        Date fecha_1 = new Date();
        int validacion = 0;
        String nombre_empleado, area;
        String fecha = "";
        nombre_empleado = barra_empleado.getText().trim().toUpperCase();
        area = barra_area.getText().trim().toUpperCase();
        fecha = f.format(fecha_1);

        if (nombre_empleado.equals("")) {
            barra_empleado.setBackground(Color.red);
            validacion++;
        }
        if (area.equals("")) {
            barra_area.setBackground(Color.red);
            validacion++;
        }

        if (validacion == 0) {
            try {
                Connection cn = Conection_bd.conexion_bd();
                PreparedStatement pst = cn.prepareStatement("insert into responsable values(?,?,?,?)");
                pst.setInt(1, 0);
                pst.setString(2, nombre_empleado);
                pst.setString(3, "ACTIVO");
                pst.setString(4, area);
                pst.executeUpdate();
                cn.close();

            } catch (Exception e) {
                System.out.println("Error al guardar: " + e);
                //JOptionPane.showMessageDialog(Componente, mensaje, título, tipo de mensaje, icono);
                JOptionPane.showMessageDialog(null, "Error al guardar informacion\n"+e, "Error", JOptionPane.ERROR_MESSAGE);
            }
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar los campos requeridos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registrar_botonActionPerformed

    private void boton_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_regresarActionPerformed

        menuEmpleados p = new menuEmpleados();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altaResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altaResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altaResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altaResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new altaResponsable().setVisible(true);
            }
        });
    }

    public void limpiarCampos() {
        barra_area.setBackground(Color.GREEN);
        barra_empleado.setBackground(Color.GREEN);

        Icon icono_correcto = new ImageIcon(getClass().getResource("/imagenes/correcto.png"));
        int valor = JOptionPane.showConfirmDialog(null, "Se ha guardado correctamente", "Responsable registrado correctamente", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, icono_correcto);
        //int valor = JOptionPane.showConfirmDialog(null, "Se ha guardado correctamente", "Equipo registrado correctamente", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, icono_correcto);
        if (valor == JOptionPane.YES_OPTION) {
            barra_area.setText("");
            barra_empleado.setText("");
        }
        barra_area.setBackground(Color.white);
        barra_empleado.setBackground(Color.white);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barra_area;
    private javax.swing.JTextField barra_empleado;
    private javax.swing.JButton boton_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrar_boton;
    // End of variables declaration//GEN-END:variables
}
