/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conection_bd;
import static interfaces.loggin.icono;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Josue Lopez
 */
public class bajaResponsable_datos extends javax.swing.JFrame {

    public int id_responsable = 0, id = 0;
    private String actualizacion = "update responsable set "
            + "estatus_responsable=? "
            + "where id_responsable = '";

    /**
     * Creates new form bajaResponsable_datos
     */
    public bajaResponsable_datos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource(icono)).getImage());
        id_responsable = bajaResponsable_tabla.id_responsable;
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setBackground(new Color(51, 102, 255));
        try {
            Connection cn = Conection_bd.conexion_bd();
            PreparedStatement pst = cn.prepareStatement("select "
                    + "e.id_responsable, "
                    + "e.nombre_responsable, "
                    + "e.area_responsable "
                    + "from responsable e "
                    + "where e.id_responsable='" + id_responsable + "'");

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                id = rs.getInt("id_responsable");
                barra_nombre.setText(rs.getString("nombre_responsable"));
                barra_area.setText(rs.getString("area_responsable"));

            }

            cn.close();
        } catch (Exception e) {
            System.out.println("Error al llenar tabla de equipos: " + e);
            //JOptionPane.showMessageDialog(Componente, mensaje, título, tipo de mensaje, icono);
            JOptionPane.showMessageDialog(null, "Error al mostrar informacion sobre equipos\n"+e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        barra_area = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        barra_nombre = new javax.swing.JLabel();
        boton_baja = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Baja responsable");
        setMinimumSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(191, 191, 191));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar_30.png"))); // NOI18N
        boton_buscar.setText("Regresar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 35));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dar de baja:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        barra_area.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        barra_area.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra_area.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(barra_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 360, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        barra_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        barra_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra_nombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(barra_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 360, 40));

        boton_baja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/baja_100.png"))); // NOI18N
        boton_baja.setMaximumSize(new java.awt.Dimension(100, 100));
        boton_baja.setMinimumSize(new java.awt.Dimension(100, 100));
        boton_baja.setPreferredSize(new java.awt.Dimension(100, 100));
        boton_baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bajaActionPerformed(evt);
            }
        });
        jPanel1.add(boton_baja, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 100, 100));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Area:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
        // TODO add your handling code here:
        bajaResponsable_tabla p = new bajaResponsable_tabla();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void boton_bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bajaActionPerformed
        // TODO add your handling code here:
        /*
        "update equipos set "
         "estado_equipo=?, "
            motivo_baja=?, 
            ultima_modificacion=? 
            where id_equipo = 
         */

        try {

            Connection cn = Conection_bd.conexion_bd();
            PreparedStatement pst = cn.prepareStatement(actualizacion + id + "'");
            pst.setString(1, "INACTIVO");
            pst.executeUpdate();
            cn.close();
        } catch (Exception e) {
            System.out.println("Error al guardar: " + e);
            //JOptionPane.showMessageDialog(Componente, mensaje, título, tipo de mensaje, icono);
            JOptionPane.showMessageDialog(null, "Error al dar de baja \n"+e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        limpiarCampos();

    }//GEN-LAST:event_boton_bajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bajaResponsable_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bajaResponsable_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bajaResponsable_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bajaResponsable_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bajaResponsable_datos().setVisible(true);
            }
        });
    }
        public void limpiarCampos() {
        Icon icono_correcto = new ImageIcon(getClass().getResource("/imagenes/correcto.png"));
        int valor = JOptionPane.showConfirmDialog(null, "Se ha actualizado la informacion correctamente", "Baja de equipo", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, icono_correcto);
        if (valor == JOptionPane.YES_OPTION) {

        }

        bajaResponsable_tabla p = new bajaResponsable_tabla();
        p.setVisible(true);
        this.dispose();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barra_area;
    private javax.swing.JLabel barra_nombre;
    private javax.swing.JButton boton_baja;
    private javax.swing.JButton boton_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
