/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import static interfaces.loggin.icono;
import javax.swing.ImageIcon;

/**
 *
 * @author Josue Lopez
 */
public class menuEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form menuEmpleados
     */
    public menuEmpleados() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource(icono)).getImage());
        menuEquipos.boton_transparente(boton_alta_responsable);
        menuEquipos.boton_transparente(boton_consultas_equipos);
        menuEquipos.boton_transparente(boton_baja_responsable);
        menuEquipos.boton_transparente(boton_modificar_responsable);
        //menuEquipos.boton_transparente(boton_cambio_responsable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_alta_responsable = new javax.swing.JButton();
        boton_consultas_equipos = new javax.swing.JButton();
        boton_baja_responsable = new javax.swing.JButton();
        boton_modificar_responsable = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        boton_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu empleados");

        jPanel1.setBackground(new java.awt.Color(191, 191, 191));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_alta_responsable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton_alta_responsable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/altas responsables_125.png"))); // NOI18N
        boton_alta_responsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_alta_responsableActionPerformed(evt);
            }
        });
        jPanel1.add(boton_alta_responsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 125, 125));

        boton_consultas_equipos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton_consultas_equipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultas responsables_125.png"))); // NOI18N
        boton_consultas_equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_consultas_equiposActionPerformed(evt);
            }
        });
        jPanel1.add(boton_consultas_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 125, 125));

        boton_baja_responsable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton_baja_responsable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bajasresponsables_125.png"))); // NOI18N
        boton_baja_responsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_baja_responsableActionPerformed(evt);
            }
        });
        jPanel1.add(boton_baja_responsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 125, 125));

        boton_modificar_responsable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton_modificar_responsable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editarempleado_125.png"))); // NOI18N
        boton_modificar_responsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificar_responsableActionPerformed(evt);
            }
        });
        jPanel1.add(boton_modificar_responsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 125, 125));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Consultas y reportes");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Alta de responsable");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Baja de responsable");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Modificar informacion");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        boton_regresar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar_30.png"))); // NOI18N
        boton_regresar.setText("Regresar");
        boton_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_regresarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_alta_responsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_alta_responsableActionPerformed
        // TODO add your handling code here:
        altaResponsable alta = new altaResponsable();
        alta.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_boton_alta_responsableActionPerformed

    private void boton_consultas_equiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_consultas_equiposActionPerformed
        // TODO add your handling code here:
        consultasReportes_responsables mbm = new consultasReportes_responsables();
        mbm.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_consultas_equiposActionPerformed

    private void boton_baja_responsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_baja_responsableActionPerformed
        // TODO add your handling code here:
        bajaResponsable_tabla baja = new bajaResponsable_tabla();
        baja.setVisible(true);
        dispose();

    }//GEN-LAST:event_boton_baja_responsableActionPerformed

    private void boton_modificar_responsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificar_responsableActionPerformed
        // TODO add your handling code here:
        modificarInformacion_responsable_tabla m = new modificarInformacion_responsable_tabla();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_modificar_responsableActionPerformed

    private void boton_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_regresarActionPerformed

        menuPrincipal p = new menuPrincipal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_alta_responsable;
    private javax.swing.JButton boton_baja_responsable;
    private javax.swing.JButton boton_consultas_equipos;
    private javax.swing.JButton boton_modificar_responsable;
    private javax.swing.JButton boton_regresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
