/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conection_bd;
import static interfaces.loggin.icono;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Josue Lopez
 */
public class verDetalles_datos extends javax.swing.JFrame implements ClipboardOwner {

    public int id_equipo = 0, id = 0;

    /**
     * Creates new form verDetalles_datos
     */
    public verDetalles_datos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource(icono)).getImage());
        id_equipo = verDetalles_tabla.id_equipo;
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setBackground(new Color(51, 102, 255));
        try {
            Connection cn = Conection_bd.conexion_bd();
            PreparedStatement pst = cn.prepareStatement("select "
                    + "e.id_equipo, "
                    + "e.tipo_equipo, "
                    + "e.ubicacion_equipo, "
                    + "e.marca_equipo, "
                    + "e.modelo_equipo, "
                    + "e.procesador_equipo, "
                    + "e.ram_equipo, "
                    + "disco_equipo, "
                    + "e.estado_equipo, "
                    + "e.perifericos_equipo, "
                    + "e.pw_equipo, "
                    + "e.ultima_modificacion "
                    + "from equipos e "
                    + "where e.id_equipo='" + id_equipo + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                id = rs.getInt("id_equipo");
                barra_tipo.setText(rs.getString("tipo_equipo"));
                barra_ubicacion.setText(rs.getString("ubicacion_equipo"));
                barra_marca.setText(rs.getString("marca_equipo"));
                barra_modelo.setText(rs.getString("modelo_equipo"));
                barra_procesador.setText(rs.getString("procesador_equipo"));
                barra_ram.setText(rs.getString("ram_equipo"));
                barra_disco.setText(rs.getString("disco_equipo"));
                barra_perifericos.setText(rs.getString("perifericos_equipo"));
                barra_fecha.setText(rs.getString("ultima_modificacion"));
                barra_contra.setText(rs.getString("pw_equipo"));

            }

            cn.close();
        } catch (Exception e) {
            System.out.println("Error al llenar tabla de equipos: " + e);
            //JOptionPane.showMessageDialog(Componente, mensaje, título, tipo de mensaje, icono);
            JOptionPane.showMessageDialog(null, "Error al mostrar informacion sobre equipos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        boton_buscar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        barra_fecha = new javax.swing.JLabel();
        barra_perifericos = new javax.swing.JLabel();
        barra_disco = new javax.swing.JLabel();
        barra_ram = new javax.swing.JLabel();
        barra_procesador = new javax.swing.JLabel();
        barra_modelo = new javax.swing.JLabel();
        barra_marca = new javax.swing.JLabel();
        barra_ubicacion = new javax.swing.JLabel();
        barra_tipo = new javax.swing.JLabel();
        copiar_ubicacion = new javax.swing.JButton();
        copiar_disco = new javax.swing.JButton();
        copiar_ram = new javax.swing.JButton();
        copiar_procesador = new javax.swing.JButton();
        copiar_modelo = new javax.swing.JButton();
        copiar_marca = new javax.swing.JButton();
        copiar_tipo = new javax.swing.JButton();
        copiar_perifericos = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        barra_contra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ver detalles equipos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(191, 191, 191));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Tipo de equipo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 118, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Ubicacion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 98, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Procesador:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 86, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Memoria ram:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Disco duro:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 98, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Marca:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 98, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ultima modificacion:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 150, -1));

        boton_buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar_30.png"))); // NOI18N
        boton_buscar.setText("Regresar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 35));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Modelo:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 98, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 98, -1));

        barra_fecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        barra_fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra_fecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(barra_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 150, 40));

        barra_perifericos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_perifericos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra_perifericos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(barra_perifericos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 210, 30));

        barra_disco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_disco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra_disco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(barra_disco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 210, 30));

        barra_ram.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_ram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra_ram.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(barra_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 210, 30));

        barra_procesador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_procesador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra_procesador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(barra_procesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 210, 30));

        barra_modelo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_modelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra_modelo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(barra_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 210, 30));

        barra_marca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_marca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra_marca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(barra_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 210, 30));

        barra_ubicacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_ubicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra_ubicacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(barra_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 210, 30));

        barra_tipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra_tipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(barra_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 210, 30));

        copiar_ubicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        copiar_ubicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/copiar_15.png"))); // NOI18N
        copiar_ubicacion.setText("Copiar");
        copiar_ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiar_ubicacionActionPerformed(evt);
            }
        });
        jPanel1.add(copiar_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, 30));

        copiar_disco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        copiar_disco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/copiar_15.png"))); // NOI18N
        copiar_disco.setText("Copiar");
        copiar_disco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiar_discoActionPerformed(evt);
            }
        });
        jPanel1.add(copiar_disco, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, 30));

        copiar_ram.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        copiar_ram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/copiar_15.png"))); // NOI18N
        copiar_ram.setText("Copiar");
        copiar_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiar_ramActionPerformed(evt);
            }
        });
        jPanel1.add(copiar_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, 30));

        copiar_procesador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        copiar_procesador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/copiar_15.png"))); // NOI18N
        copiar_procesador.setText("Copiar");
        copiar_procesador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiar_procesadorActionPerformed(evt);
            }
        });
        jPanel1.add(copiar_procesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, 30));

        copiar_modelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        copiar_modelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/copiar_15.png"))); // NOI18N
        copiar_modelo.setText("Copiar");
        copiar_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiar_modeloActionPerformed(evt);
            }
        });
        jPanel1.add(copiar_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, 30));

        copiar_marca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        copiar_marca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/copiar_15.png"))); // NOI18N
        copiar_marca.setText("Copiar");
        copiar_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiar_marcaActionPerformed(evt);
            }
        });
        jPanel1.add(copiar_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, 30));

        copiar_tipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        copiar_tipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/copiar_15.png"))); // NOI18N
        copiar_tipo.setText("Copiar");
        copiar_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiar_tipoActionPerformed(evt);
            }
        });
        jPanel1.add(copiar_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, 30));

        copiar_perifericos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        copiar_perifericos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/copiar_15.png"))); // NOI18N
        copiar_perifericos.setText("Copiar");
        copiar_perifericos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiar_perifericosActionPerformed(evt);
            }
        });
        jPanel1.add(copiar_perifericos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Perifericos:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 98, -1));

        barra_contra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barra_contra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra_contra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(barra_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
        // TODO add your handling code here:
        verDetalles_tabla p = new verDetalles_tabla();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void copiar_ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiar_ubicacionActionPerformed
        // TODO add your handling code here:
        copiar(barra_ubicacion.getText());
    }//GEN-LAST:event_copiar_ubicacionActionPerformed

    private void copiar_discoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiar_discoActionPerformed
        // TODO add your handling code here:
        copiar(barra_disco.getText());
    }//GEN-LAST:event_copiar_discoActionPerformed

    private void copiar_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiar_ramActionPerformed
        // TODO add your handling code here:
        copiar(barra_ram.getText());
    }//GEN-LAST:event_copiar_ramActionPerformed

    private void copiar_procesadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiar_procesadorActionPerformed
        // TODO add your handling code here:
        copiar(barra_procesador.getText());
    }//GEN-LAST:event_copiar_procesadorActionPerformed

    private void copiar_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiar_modeloActionPerformed
        // TODO add your handling code here:
        copiar(barra_modelo.getText());
    }//GEN-LAST:event_copiar_modeloActionPerformed

    private void copiar_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiar_marcaActionPerformed
        // TODO add your handling code here:
        copiar(barra_marca.getText());
    }//GEN-LAST:event_copiar_marcaActionPerformed

    private void copiar_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiar_tipoActionPerformed
        // TODO add your handling code here:
        copiar(barra_tipo.getText());
    }//GEN-LAST:event_copiar_tipoActionPerformed

    private void copiar_perifericosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiar_perifericosActionPerformed
        // TODO add your handling code here:
        copiar(barra_perifericos.getText());
    }//GEN-LAST:event_copiar_perifericosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verDetalles_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verDetalles_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verDetalles_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verDetalles_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verDetalles_datos().setVisible(true);
            }
        });
    }

    public void copiar(String texto) {//primero copiar implemnets
        StringSelection txt = new StringSelection(texto);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(txt, this);
    }

    @Override
    public void lostOwnership(Clipboard clpbrd, Transferable t) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barra_contra;
    private javax.swing.JLabel barra_disco;
    private javax.swing.JLabel barra_fecha;
    private javax.swing.JLabel barra_marca;
    private javax.swing.JLabel barra_modelo;
    private javax.swing.JLabel barra_perifericos;
    private javax.swing.JLabel barra_procesador;
    private javax.swing.JLabel barra_ram;
    private javax.swing.JLabel barra_tipo;
    private javax.swing.JLabel barra_ubicacion;
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton copiar_disco;
    private javax.swing.JButton copiar_marca;
    private javax.swing.JButton copiar_modelo;
    private javax.swing.JButton copiar_perifericos;
    private javax.swing.JButton copiar_procesador;
    private javax.swing.JButton copiar_ram;
    private javax.swing.JButton copiar_tipo;
    private javax.swing.JButton copiar_ubicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
